#################################################
# Core config
#################################################

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 172.16.16.0/24
      trusted_users:
        172.16.16.0/24: 5eb99a825ace48779fad323aac28014d
  name: Home, Sweeet Home...
  time_zone: !secret home_timezone
  unit_system: metric
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages
  allowlist_external_dirs:
    - /config/
    - /config/www/weather_icons/
    - /config/www/cam_snapshots/

#################################################
# Features
#################################################

api:
config:
hassio:
system_health:
stream:
zeroconf:
ssdp:
sun:
map:
mobile_app:
#wwlln:
wake_on_lan:
person:
logbook:
history:
tag:
media_source:
my:
dhcp:
image:

http:
  #base_url: !secret external_url
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - 172.16.16.253
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warn
#  logs:
#    homeassistant.components.tuya: debug
#    homeassistant.components.http.ban: warning
#    homeassistant.components.device_tracker: debug

system_log:
  max_entries: 50
  fire_event: true

frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret mysql_url
  purge_keep_days: 7
  commit_interval: 60
  exclude:
    domains:
      - updater
      - automation
      - script
      - camera
      - input_datetime
      - input_number
      - input_select
    entity_globs:
      - sensor.*_zigbee
      - sensor.*_ble
      - sensor.keenetic_gateway_*
      - sensor.*_poslednee_uvedomlenie
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time_iso
      - sensor.date_formatted
      - sensor.uptime
      - sensor.moon
      - sun.sun
      - counter.syslog_errors
      - counter.syslog_warnings
    event_types:
      - call_service

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 5
  default_measurement: state
  tags_attributes:
    - friendly_name
  include:
    entities: !include influxdb_conf/influxdb_include_entities.yaml
    entity_globs: !include influxdb_conf/influxdb_include_entity_globs.yaml
  component_config_glob:
    sensor.*_zigbee:
      ignore_attributes:
        - state
        - msg_received
        - last_msg

lovelace: !include lovelace/lovelace.yaml

tts:
  - platform: google_translate
    language: 'ru'

weather:
  - platform: gismeteo
    mode: daily

discovery:
  ignore:
    - homekit
#    - yeelight
#    - igd

light:
  - platform: switch
    name: Детская - подсветка на окне
    entity_id: switch.0x158d00033b702e_switch
  - platform: switch
    name: Гостиная - подсветка на окне
    entity_id: switch.0x158d000391fb00_switch

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_pass
  devices:
    1000b6831b:
      devicekey: 87c5267d-054f-4a71-8c51-49d027b80d71
      device_class: light
    1000b72483:
      devicekey: bed13aa0-97b7-4177-9b8e-922167e60aea
      device_class: light
    1000ab3c28:
      devicekey: 4158540f-d7c0-4453-aeac-958355a85756
      device_class: light
    1000f3035d:
      devicekey: 71f2d399-79e7-4bf4-9543-1420a806dda7
      device_class: light
    1000f30a9e:
      devicekey: 10541ed9-c3bd-476e-9229-3c852bbfcfe5
      device_class: light
    1000f2f14a:
      devicekey: b8de3a5e-fc76-4110-b8ab-2f6487d7796b
      device_class: light
    1000f2a500:
      devicekey: d32b0517-cca8-4d92-a1ef-ac9fbd4e0f0a
      device_class: light

start_time:

tplink:
  discovery: false
  switch:
    - host: 172.16.16.213
    - host: 172.16.16.216

#zabbix:
#  host: home.intra
#  username: !secret zbx_user
#  password: !secret zbx_pass

telegram_bot:
  - platform: webhooks # or "polling"
#    url: !secret tlg_webhook_proxy_url
    api_key: !secret telegram_bot_token
#    trusted_networks:
#      - !secret tlg_webhook_proxy_ip
    allowed_chat_ids:
      - !secret tlg_stall_id
      - !secret tlg_iborisochka_id

notify:
  - name: telegram_stall
    platform: telegram
    chat_id: !secret tlg_stall_id
  - name: telegram_iborisochka
    platform: telegram
    chat_id: !secret tlg_iborisochka_id

#################################################
# Inclusions
#################################################

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
camera: !include_dir_merge_list entities/cameras
counter: !include_dir_merge_named entities/counters
device_tracker: !include_dir_merge_list entities/device_trackers
sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
switch: !include_dir_merge_list entities/switches
media_player: !include_dir_merge_list entities/media_players
input_select: !include_dir_merge_named entities/input_select
input_number: !include_dir_merge_named entities/input_number
input_datetime: !include_dir_merge_named entities/input_datetime
input_boolean: !include_dir_merge_named entities/input_boolean
input_text: !include_dir_merge_named entities/input_text
shell_command: !include_dir_merge_named entities/shell_commands
rest_command: !include_dir_merge_named entities/rest_command
yeelight: !include entities/yeelight/yeelight.yaml