#################################################
# Thermo & Climate Automations
#################################################

# Детская #######################################
- alias: Termo alert [Nursery]
  id: bb3a7df3-3e20-4ebe-8b49-bc9ba69ad2b6
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931aec_temperature') | float) < 22 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931aec_temperature') | float) > 25 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Детской*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Гостиная ######################################
- alias: Termo alert [Living Room]
  id: 0e135e8d-3ad5-40cb-9d8f-9ab3df6b91bd
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003230618_temperature') | float) < 22 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003230618_temperature') | float) > 25 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Гостиной*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Спальня #######################################
- alias: Termo alert [Bedroom]
  id: 524b5b92-0f5d-4429-88d2-9903ec325389
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931b0e_temperature') | float) < 21 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931b0e_temperature') | float) > 24.5 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Спальне*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Оповещения о долгой работе кондиционеров ######
- alias: AC - long running [8h]
  id: 09f64418-db04-4327-a714-57d9ea39d1ed
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 8
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше 8 часов.

- alias: AC - long running [16h]
  id: 970eef7a-4b66-4186-88ff-a0542c13c10a
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 16
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше *16* часов.

- alias: AC - long running [24h]
  id: 106513d8-941c-4bfe-8f42-1fe9c95a77de
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 24
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше *24* часов.