#################################################
# Automations for Humidor (Smoking kills!)
#################################################

- alias: 'Humidity in humidor too low'
  id: 4ccbd0aa-829a-45d3-abe7-33ae2552215b
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.a4c1381b3d13_humidity
    below: 65
    for:
      minutes: 30
  action:
    - service: notify.telegram_stall
      data:
        message: Влажность в хьюмидоре ниже 65% (текущая {{ states("sensor.a4c1381b3d13_humidity") }}%)

- alias: 'Humidity in humidor too high'
  id: f6158c69-c088-4258-a623-6c2ee3c2cf72
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.a4c1381b3d13_humidity
    above: 80
    for:
      minutes: 30
  action:
    - service: notify.telegram_stall
      data:
        message: Влажность в хьюмидоре выше 80% (текущая {{ states("sensor.a4c1381b3d13_humidity") }}%)

- alias: 'Temperature in humidor too low'
  id: 0d95f393-ab18-4aef-8eb9-9bf5165d6638
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.a4c1381b3d13_temperature
    below: 20
    for:
      minutes: 30
  action:
    - service: notify.telegram_stall
      data:
        message: Температура в хьюмидоре ниже 20°C (текущая {{ states("sensor.a4c1381b3d13_temperature") }}°C)

- alias: 'Temperature in humidor too high'
  id: dcfce935-f705-4ae5-be45-ffb780b3f290
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.a4c1381b3d13_temperature
    above: 25
    for:
      minutes: 30
  action:
    - service: notify.telegram_stall
      data:
        message: Температура в хьюмидоре выше 25°C (текущая {{ states("sensor.a4c1381b3d13_temperature") }}°C)