#################################################
# Media automatization
#################################################

- alias: "PowerOff all media when nobody at home"
  id: 0e2312c7-3cab-413a-aefb-20ff5802c718
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_tv
        state: "on"
      - condition: state
        entity_id: group.all_chromecasts
        state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_tv
    - service: media_player.media_stop
      data:
        entity_id: group.all_chromecasts

- alias: "Wakeup Radio - Childrens"
  id: 75d1f4fc-c40b-433a-b6bc-ed480b53365e
  initial_state: true
  trigger:
    platform: time
    at: input_datetime.wakeup_radio_in_nursery
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  action:
    - service: media_player.volume_set
      entity_id: media_player.googlehome3792
      data:
        volume_level: "0.1"
    - service: media_player.play_media
      data:
        entity_id: media_player.googlehome3792
        media_content_id: "http://ic7.101.ru:8000/a199"
        media_content_type: music
    - alias: Increase volume by 5%
      repeat:
        while:
          - condition: template
            value_template: "{{ repeat.index <= 5 }}"
        sequence:
          - delay: "00:03:00"
          - service: media_player.volume_set
            entity_id: media_player.googlehome3792
            data_template:
              volume_level: >
                {% set level = (state_attr('media_player.googlehome3792', 'volume_level') | float) + (0.05 | float) %}
                {% if level < 1 %} {{ level }}
                {% else %} 1
                {% endif %}